"use strict";

const state={socket:null,manualClose:false,reconnectTimer:null,vehicles:new Map(),targets:new Map(),sensors:new Map(),gateway:{},messageTimes:[],typeStats:new Map(),messages:0,lastMessage:0,jsonPaused:false,scale:6,panX:0,panY:0,drag:null};
const el=id=>document.getElementById(id);
const protocol=window.location.protocol==="https:"?"wss":"ws";
el("wsUrl").value=`${protocol}://${window.location.hostname}:8765/ws`;
const fmt=(value,digits=2)=>value===null||value===undefined||Number.isNaN(Number(value))?"不可用":Number(value).toFixed(digits);
const age=stamp=>!stamp?"不可用":`${Math.max(0,Date.now()/1000-stamp).toFixed(1)} s前`;
const safe=value=>String(value??"不可用").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));

function setConnection(text,kind){el("connectionBadge").textContent=text;el("connectionBadge").className=`badge ${kind}`;}
function connect(){disconnect(false);state.manualClose=false;const url=el("wsUrl").value.trim();if(!url)return;setConnection("正在连接","connecting");el("serverText").textContent=url;try{state.socket=new WebSocket(url);}catch(_){setConnection("连接错误","offline");scheduleReconnect();return}state.socket.onopen=()=>setConnection("已连接","online");state.socket.onmessage=e=>handleMessage(e.data);state.socket.onerror=()=>setConnection("连接错误","offline");state.socket.onclose=()=>{setConnection("已断开","offline");state.socket=null;scheduleReconnect();};}
function disconnect(manual=true){state.manualClose=manual;clearTimeout(state.reconnectTimer);if(state.socket){state.socket.onclose=null;state.socket.close();state.socket=null;}if(manual)setConnection("未连接","offline");}
function scheduleReconnect(){clearTimeout(state.reconnectTimer);if(!state.manualClose&&el("autoReconnect").checked)state.reconnectTimer=setTimeout(connect,2000);}
function send(command){if(state.socket&&state.socket.readyState===WebSocket.OPEN)state.socket.send(JSON.stringify({command}));}

function handleMessage(raw){let message;try{message=JSON.parse(raw);}catch(_){return}state.messages++;state.lastMessage=Date.now();state.messageTimes.push(state.lastMessage);state.messageTimes=state.messageTimes.filter(t=>state.lastMessage-t<5000);recordMessageType(message.message_type);if(!state.jsonPaused){el("rawJson").textContent=JSON.stringify(message,null,2);if(el("autoScroll").checked)el("rawJson").scrollTop=el("rawJson").scrollHeight;}const data=message.data||{};switch(message.message_type){case"fleet_snapshot":applySnapshot(data);break;case"vehicle_state":upsert(state.vehicles,data.id,data);renderVehicles();break;case"perception_targets":el("perceptionSource").textContent=data.selected_source||data.source||"未知";replaceTargets(data.targets||[]);break;case"sensor_status":upsert(state.sensors,`${data.vehicle_id}/${data.sensor_id}`,data);renderSensors();break;case"gateway_diagnostics":state.gateway=data;renderGateway();break;}updateSummary();drawMap();}
function recordMessageType(type){const key=type||"unknown",now=Date.now(),stats=state.typeStats.get(key)||{count:0,last:0,times:[]};stats.count++;stats.last=now;stats.times.push(now);stats.times=stats.times.filter(value=>now-value<5000);state.typeStats.set(key,stats);}
function upsert(map,key,value){if(key)map.set(key,value);}
function applySnapshot(data){state.vehicles.clear();(data.vehicles||[]).forEach(v=>upsert(state.vehicles,v.id,v));replaceTargets(data.targets||[]);state.sensors.clear();(data.sensors||[]).forEach(s=>upsert(state.sensors,`${s.vehicle_id}/${s.sensor_id}`,s));state.gateway=data.gateway||{};renderVehicles();renderSensors();renderGateway();}
function replaceTargets(targets){state.targets.clear();targets.forEach(t=>upsert(state.targets,t.track_id,t));renderTargets();}
function row(label,value){return `<div><span>${safe(label)}：</span>${safe(value)}</div>`;}
function renderVehicles(){const root=el("vehicleCards");const values=[...state.vehicles.values()].sort((a,b)=>a.id.localeCompare(b.id));el("vehicleSummary").textContent=`${values.length} 艘/架`;root.className=values.length?"card-grid":"card-grid empty";root.innerHTML=values.map(v=>{const p=v.position||{},o=v.orientation||{},b=v.battery||{};const status=v.stale?"stale":v.online?"online":"";return `<article class="data-card"><div class="card-head"><strong>${safe(v.id)} · ${safe(v.type)}</strong><span class="state-dot ${status}">${v.stale?"数据陈旧":v.online?"在线":"离线"}</span></div><div class="rows">${row("位置",`${fmt(p.x)}, ${fmt(p.y)}, ${fmt(p.z)}`)}${row("姿态",`${fmt(o.roll)}, ${fmt(o.pitch)}, ${fmt(o.yaw)}`)}${row("速度",`${fmt(v.speed)} m/s`)}${row("电量",b.percentage===null?"不可用":`${fmt(b.percentage,1)}%`)}${row("模式",v.mode)}${row("解锁",v.armed===null?"不可用":v.armed?"是":"否")}${row("坐标系",v.frame_id)}${row("更新",age(v.last_update))}</div></article>`;}).join("")||"等待载具状态";}
function renderTargets(){const root=el("targetCards");const values=[...state.targets.values()];root.className=values.length?"card-grid":"card-grid empty";root.innerHTML=values.map(t=>{const p=t.position||{},v=t.velocity||{},b=t.bbox||{};return `<article class="data-card"><div class="card-head"><strong>${safe(t.track_id)}</strong><span>${safe(t.class_name)}</span></div><div class="rows">${row("来源",t.sensor_source||t.source)}${row("置信度",fmt(t.confidence,2))}${row("位置",`${fmt(p.x)}, ${fmt(p.y)}, ${fmt(p.z)}`)}${row("速度",`${fmt(v.x)}, ${fmt(v.y)}, ${fmt(v.z)}`)}${row("尺寸",`${fmt(b.length)} × ${fmt(b.width)} × ${fmt(b.height)}`)}${row("坐标系",t.frame_id)}${row("更新",age(t.timestamp))}</div></article>`;}).join("")||"等待目标数据";}
function renderSensors(){const root=el("sensorCards");const values=[...state.sensors.values()];root.className=values.length?"card-grid":"card-grid empty";root.innerHTML=values.map(s=>`<article class="data-card"><div class="card-head"><strong>${safe(s.vehicle_id)} / ${safe(s.sensor_id)}</strong><span class="state-dot ${s.online?"online":""}">${safe(s.status)}</span></div><div class="rows">${row("类型",s.sensor_type)}${row("频率",`${fmt(s.frequency_hz,1)} Hz`)}${row("点数",s.point_count)}${row("延迟",`${fmt(s.latency_sec,3)} s`)}${row("坐标系",s.frame_id)}${row("更新",age(s.last_update))}</div></article>`).join("")||"等待传感器状态";}
function renderGateway(){const labels={connected_clients:"浏览器客户端",registered_vehicles:"注册载具",online_vehicles:"在线载具",stale_vehicles:"陈旧载具",target_count:"目标",received_messages:"ROS接收消息",sent_messages:"已发送",dropped_messages:"已丢弃",uptime_sec:"运行秒数",websocket_running:"WebSocket"};el("gatewayGrid").innerHTML=Object.entries(labels).map(([key,label])=>`<div class="detail"><span>${label}</span><strong>${safe(state.gateway[key]??"不可用")}</strong></div>`).join("");}
function updateSummary(){const now=Date.now();state.messageTimes=state.messageTimes.filter(value=>now-value<5000);el("messageCount").textContent=state.messages;el("lastMessage").textContent=state.lastMessage?new Date(state.lastMessage).toLocaleTimeString():"--";el("receiveRate").textContent=`${(state.messageTimes.length/5).toFixed(1)} Hz`;el("onlineCount").textContent=[...state.vehicles.values()].filter(v=>v.online&&!v.stale).length;el("targetCount").textContent=state.targets.size;renderMessageTypes(now);}
function renderMessageTypes(now){const root=el("messageTypeGrid"),entries=[...state.typeStats.entries()].sort((a,b)=>a[0].localeCompare(b[0]));root.innerHTML=entries.map(([type,stats])=>{stats.times=stats.times.filter(value=>now-value<5000);const hz=(stats.times.length/5).toFixed(1),updated=stats.last?new Date(stats.last).toLocaleTimeString():"--";return `<div class="detail"><span>${safe(type)}</span><strong>${hz} Hz</strong><small>${stats.count} 条 · ${updated}</small></div>`;}).join("")||'<div class="detail"><span>等待 WebSocket 数据</span><strong>--</strong></div>';}

const canvas=el("fleetMap"),ctx=canvas.getContext("2d");
function resizeCanvas(){const dpr=Math.min(window.devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();const w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.setTransform(dpr,0,0,dpr,0,0);drawMap();}
function worldToCanvas(x,y){const r=canvas.getBoundingClientRect();return [r.width/2+state.panX+x*state.scale,r.height/2+state.panY-y*state.scale];}
function drawMap(){const r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle="#111a20";ctx.fillRect(0,0,r.width,r.height);if(el("showGrid").checked)drawGrid(r);for(const v of state.vehicles.values())drawVehicle(v);for(const t of state.targets.values())drawTarget(t);}
function drawGrid(r){const spacing=Math.max(20,state.scale*10),ox=((r.width/2+state.panX)%spacing+spacing)%spacing,oy=((r.height/2+state.panY)%spacing+spacing)%spacing;ctx.strokeStyle="#2a3a44";ctx.lineWidth=1;ctx.beginPath();for(let x=ox;x<r.width;x+=spacing){ctx.moveTo(x,0);ctx.lineTo(x,r.height)}for(let y=oy;y<r.height;y+=spacing){ctx.moveTo(0,y);ctx.lineTo(r.width,y)}ctx.stroke();ctx.strokeStyle="#536873";ctx.beginPath();const [x0,y0]=worldToCanvas(0,0);ctx.moveTo(x0,0);ctx.lineTo(x0,r.height);ctx.moveTo(0,y0);ctx.lineTo(r.width,y0);ctx.stroke();}
function drawVehicle(v){const p=v.position||{},o=v.orientation||{},x=Number(p.x),y=Number(p.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const [cx,cy]=worldToCanvas(x,y),yaw=Number(o.yaw)||0;ctx.save();ctx.translate(cx,cy);ctx.rotate(-yaw);ctx.fillStyle=v.type==="UAV"?"#4ca7ff":"#ffd057";ctx.strokeStyle="#101820";ctx.lineWidth=1.5;ctx.beginPath();if(v.type==="UAV"){ctx.moveTo(12,0);ctx.lineTo(-8,-7);ctx.lineTo(-5,0);ctx.lineTo(-8,7);}else{ctx.rect(-10,-6,20,12);ctx.moveTo(10,-6);ctx.lineTo(15,0);ctx.lineTo(10,6);}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();drawLabel(v.id,cx+10,cy-10,v.stale?"#d9a441":"#eaf5fa");drawVelocity(v.linear_velocity,cx,cy);}
function drawTarget(t){const p=t.position||{},x=Number(p.x),y=Number(p.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const [cx,cy]=worldToCanvas(x,y),b=t.bbox||{},w=Math.max(10,Number(b.length||3)*state.scale),h=Math.max(8,Number(b.width||2)*state.scale);ctx.save();ctx.translate(cx,cy);ctx.rotate(-(Number(b.yaw)||0));ctx.strokeStyle="#ff5a60";ctx.lineWidth=2;ctx.strokeRect(-w/2,-h/2,w,h);ctx.restore();drawLabel(t.track_id,cx+8,cy-9,"#ff8a8f");drawVelocity(t.velocity,cx,cy);}
function drawVelocity(v,cx,cy){if(!v)return;const vx=Number(v.x),vy=Number(v.y);if(!Number.isFinite(vx)||!Number.isFinite(vy))return;ctx.strokeStyle="#62d9c7";ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+vx*state.scale*2,cy-vy*state.scale*2);ctx.stroke();}
function drawLabel(text,x,y,color){ctx.font="12px system-ui";ctx.fillStyle=color;ctx.fillText(text,x,y);}
function zoom(factor){state.scale=Math.min(40,Math.max(1,state.scale*factor));drawMap();}
canvas.addEventListener("wheel",e=>{e.preventDefault();zoom(e.deltaY<0?1.15:.87)},{passive:false});canvas.addEventListener("pointerdown",e=>{state.drag={x:e.clientX,y:e.clientY,px:state.panX,py:state.panY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(state.drag){state.panX=state.drag.px+e.clientX-state.drag.x;state.panY=state.drag.py+e.clientY-state.drag.y;drawMap()}});canvas.addEventListener("pointerup",()=>state.drag=null);
el("connectButton").onclick=connect;el("disconnectButton").onclick=()=>disconnect(true);el("snapshotButton").onclick=()=>send("request_snapshot");el("zoomIn").onclick=()=>zoom(1.2);el("zoomOut").onclick=()=>zoom(.8);el("resetView").onclick=()=>{state.scale=6;state.panX=state.panY=0;drawMap()};el("showGrid").onchange=drawMap;el("pauseJson").onclick=()=>{state.jsonPaused=!state.jsonPaused;el("pauseJson").textContent=state.jsonPaused?"恢复":"暂停"};el("clearJson").onclick=()=>el("rawJson").textContent="";window.addEventListener("resize",resizeCanvas);window.addEventListener("beforeunload",()=>disconnect(true));
renderGateway();resizeCanvas();connect();setInterval(updateSummary,1000);setInterval(()=>send("ping"),10000);
