#!/usr/bin/env python3
"""Generate the DART-safe Catalina terrain collision OBJ from its glTF.

Gazebo Sim 8 can render the source glTF, but DART's ODE collision backend
crashes when that glTF is used directly as a collision shape.  A static OBJ
with one explicit normal per vertex is accepted by the same backend.  Flat
zero-height ocean triangles are omitted because the world already owns an
ocean-plane collision.
"""

import argparse
import json
import math
import struct
from pathlib import Path


COMPONENT_FORMATS = {
    5125: 'I',
    5126: 'f',
}
TYPE_WIDTHS = {
    'SCALAR': 1,
    'VEC3': 3,
}


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--gltf', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--land-threshold', type=float, default=0.0)
    return parser.parse_args()


def accessor_values(document, binary, accessor_index):
    accessor = document['accessors'][accessor_index]
    view = document['bufferViews'][accessor['bufferView']]
    offset = view.get('byteOffset', 0) + accessor.get('byteOffset', 0)
    component_format = COMPONENT_FORMATS[accessor['componentType']]
    width = TYPE_WIDTHS[accessor['type']]
    packed_format = '<' + component_format * width
    stride = view.get('byteStride', struct.calcsize(packed_format))
    return [
        struct.unpack_from(packed_format, binary, offset + index * stride)
        for index in range(accessor['count'])
    ]


def terrain_offset(document):
    for node in document.get('nodes', []):
        if node.get('name') != 'skfb_offset':
            continue
        matrix = node.get('matrix')
        if matrix and len(matrix) == 16:
            return matrix[12], matrix[13], matrix[14]
        translation = node.get('translation', (0.0, 0.0, 0.0))
        return tuple(translation)
    raise RuntimeError('Catalina glTF has no skfb_offset node')


def cross(a, b, c):
    u = tuple(b[index] - a[index] for index in range(3))
    v = tuple(c[index] - a[index] for index in range(3))
    return (
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    )


def normalize(vector):
    length = math.sqrt(sum(value * value for value in vector))
    if length < 1e-12:
        return 0.0, 0.0, 1.0
    return tuple(value / length for value in vector)


def main():
    args = parse_args()
    document = json.loads(args.gltf.read_text(encoding='utf-8'))
    primitive = document['meshes'][0]['primitives'][0]
    if primitive.get('mode', 4) != 4:
        raise RuntimeError('Catalina terrain primitive is not triangles')

    binary_uri = document['buffers'][0]['uri']
    binary = (args.gltf.parent / binary_uri).read_bytes()
    source_positions = accessor_values(
        document,
        binary,
        primitive['attributes']['POSITION'],
    )
    source_indices = [
        value[0]
        for value in accessor_values(
            document,
            binary,
            primitive['indices'],
        )
    ]

    offset_x, offset_y, offset_z = terrain_offset(document)
    # The glTF root maps source Z-up to glTF Y-up. Gazebo converts it back to
    # Z-up while mirroring glTF's forward axis, so source V becomes -Gazebo Y.
    positions = [
        (
            position[0] + offset_x,
            -(position[1] + offset_y),
            position[2] + offset_z,
        )
        for position in source_positions
    ]

    triangles = []
    referenced = set()
    for start in range(0, len(source_indices), 3):
        triangle = tuple(source_indices[start:start + 3])
        if max(positions[index][2] for index in triangle) <= args.land_threshold:
            continue
        normal = cross(*(positions[index] for index in triangle))
        if normal[2] < 0.0:
            triangle = triangle[0], triangle[2], triangle[1]
        triangles.append(triangle)
        referenced.update(triangle)

    ordered_indices = sorted(referenced)
    remap = {
        source_index: output_index
        for output_index, source_index in enumerate(ordered_indices, start=1)
    }
    vertices = [positions[index] for index in ordered_indices]
    accumulated_normals = [[0.0, 0.0, 0.0] for _ in vertices]
    for triangle in triangles:
        output_indices = [remap[index] - 1 for index in triangle]
        normal = cross(*(vertices[index] for index in output_indices))
        for output_index in output_indices:
            for axis in range(3):
                accumulated_normals[output_index][axis] += normal[axis]
    normals = [normalize(normal) for normal in accumulated_normals]

    lines = [
        '# Generated by generate_catalina_collision_mesh.py',
        '# Source: Catalina scene.gltf; flat ocean triangles removed',
        'o catalina_terrain_collision',
    ]
    lines.extend(
        f'v {x:.6f} {y:.6f} {z:.6f}'
        for x, y, z in vertices
    )
    lines.extend(
        f'vn {x:.9f} {y:.9f} {z:.9f}'
        for x, y, z in normals
    )
    for triangle in triangles:
        a, b, c = (remap[index] for index in triangle)
        lines.append(f'f {a}//{a} {b}//{b} {c}//{c}')

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(
        'Generated Catalina collision mesh: '
        f'{len(vertices)} vertices, {len(triangles)} triangles, '
        f'{len(normals)} normals'
    )


if __name__ == '__main__':
    main()
